spring:
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    cassandra:
      port: 9041
      contact-points:
        - 127.0.0.1
      keyspace-name: maid
  security:
    jwt:
      enable-cors: true
      secret-key: DB7A9CF3-4D9B-4526-B3A2-9E1761D8F1B8
      # 3600 * 24 * 3
      max-age: 259200
      orderly-anonymous-inspections:
        - permitted-urls:
            - /**
        - authenticated-urls:
            - /v1/**
        - permitted-urls:
            - /*/auth/**

app:
  auth:
    key-prefix: maid:cassandra
    max-age:
      # 60 seconds
      image-code: 60
      # 10 * 60 seconds
      register-access-token: 600
      password-reset-access-token: 600
  file-path:
    # API
    temp-upload: /Users/tuke/data/maid/temp/upload
    temp-update: /Users/tuke/data/maid/temp/update
    # path to upload file to hub
    upload: /Users/tuke/data/maid/upload
  rest:
    sign-key: 2C45435E-C680-4B3A-A99B-5319541B24A6
server:
  port: 1131
